### ISSUE TITLE
Not running PMD, as autoBuilding is enabled for this workspace

### ISSUE THREAD

**Issue by aktion-hip** [pmd/pmd-eclipse-plugin#10]
I see that in the newest version of the plug in, the possibility to run PMD when the file is saved has been disabled if the Eclipse workspace is configured to build automatically.
See *net.sourceforge.pmd.eclipse.plugin.FileChangeReviewer*:
```java
if (workspaceSettings.isAutoBuilding()) {
    PMDPlugin.getDefault().logInformation("Not running PMD, as autoBuilding is enabled for this workspace");
    return;
}
```
What’s the reason for this?
With this, the PMD setting “Check code after saving” turns out to be useless in a normal Eclipse workspace.
Is it possible to remove/disable this new feature? I really like to have both, the autoBuilding capability of the workspace and the PMD code checking after saving.
Regards,
Benno

**Comment by adangel** [comment]
The change was actually meant to fix this bug: https://sourceforge.net/p/pmd/bugs/1350/
...

**Comment by phoenix384** [comment]
As already said in https://sourceforge.net/p/pmd/bugs/1350/ the checking of modified files now only works if "Full build enabled" is also selected.
It won't work in an auto building workspace if you disabled "Full build enabled", because you don't want PMD to check everything on a full build.

In my opinion this situation is worse than the supposed double check that https://sourceforge.net/p/pmd/bugs/1350/ was meant to fix.
As long as there is no better solution I would appreciate reverting that change:
https://github.com/pmd/pmd-eclipse-plugin/pull/11

**Comment by adangel** [comment]
Hi, I think, I've fixed the problem, see: https://sourceforge.net/p/pmd/bugs/1435/

You can install a pmd eclipse plugin version with this bugfix from:
https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/

Please let me know, if this problem is fixed for you, thanks!

**Comment by adangel** [comment]
Latest released version is available:
https://github.com/pmd/pmd-eclipse-plugin/releases/tag/4.0.8.v20151204-2156
