### ISSUE TITLE
Installation Error: bundle ch.qos.logback.* not found

### ISSUE THREAD

**Issue by wtsiamruk** [pmd/pmd-eclipse-plugin#120]
During Installation process described in 
https://pmd.github.io/latest/pmd_userdocs_tools.html#eclipse

I have issues installing the plugin:

An error occurred while collecting items to be installed
session context was:(profile=IBM Software Delivery Platform com.ibm.sdp.eclipse.ide, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,ch.qos.logback.classic,1.0.7.v20121108-1250
No repository found containing: osgi.bundle,ch.qos.logback.core,1.0.7.v20121108-1250
No repository found containing: osgi.bundle,javax.ejb,3.1.1.v201204261316
No repository found containing: osgi.bundle,javax.servlet,3.0.0.v201112011016
No repository found containing: osgi.bundle,javax.xml.bind,2.2.0.v201105210648
No repository found containing: osgi.bundle,javax.xml.ws,2.1.0.v200902101523
No repository found containing: osgi.bundle,org.apache.catalina,7.0.35.v201302131125
No repository found containing: osgi.bundle,org.apache.coyote,7.0.35.v201302140645
No repository found containing: osgi.bundle,org.apache.el,7.0.35.v201302120746
No repository found containing: osgi.bundle,org.apache.jasper,7.0.35.v201302161127
No repository found containing: osgi.bundle,org.apache.juli.extras,7.0.35.v201302120746
No repository found containing: osgi.bundle,org.apache.tomcat.api,7.0.35.v201302120746
No repository found containing: osgi.bundle,org.apache.tomcat.util,7.0.35.v201302140645
No repository found containing: osgi.bundle,org.kohsuke.args4j,2.0.21.v201301150030

Eclipse Platform

Version: 4.7.3.v20180301-0715
Build id: M20180301-0715

**Comment by wtsiamruk** [comment]
I have tried two versions below as well.

**Comment by wtsiamruk** [comment]
Installation of that version worked:

https://github.com/pmd/pmd-eclipse-plugin/releases/tag/4.5.0.v20190630-0922

**Comment by adangel** [comment]
In order to get rid of log4j eclipse-pmd-plugin depends on logback now. In newer eclipse versions, this is included via m2eclipse.

For older eclipse versions (like yours: 4.7.3), this *should* be found automatically, because I added an additional repository, where this is available:
https://github.com/pmd/pmd-eclipse-plugin/blob/397485215feed942c31563db85ef9af9cf26f752/net.sourceforge.pmd.eclipse.p2updatesite/category.xml#L11

Maybe this feature with repository-reference is not supported by eclipse 4.7.3?
Anyway, try to add "http://download.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/" as an update site before installing eclipse-pmd-plugin.
Let me know, if that works, so that we can update the docs.

**Comment by wtsiamruk** [comment]
As soon as I would set up this old eclipse again. I went through the setup external tool for IntelliJ.

**Comment by adangel** [comment]
This might be a general eclipse problem.
See comments for workaround in #124: https://github.com/pmd/pmd-eclipse-plugin/issues/124#issuecomment-650283961

You can also manually install the missing dependencies first and then install PMD Eclipse Plugin:
*   add https://archive.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/ as update site
*   install logback core, classic, and native slf4j

Not sure if that works, because if I install Eclipse 4.7.3, logback is already there...

Since this seems to be a specific from of your specific eclipse product, I can't do much more than point you to the workarounds.
