### ISSUE TITLE
Problem with ExcessiveClassLength rule

### ISSUE THREAD

**Issue by siaspa** [pmd/pmd-eclipse-plugin#30]
I have a problem with the plugin in setting the (Code Size) ExcessiveClassLength rule. In the property tab it has a property "Minimum reporting threshold" to set the number of lines of code for the file/class. It is showed with a spinner and the number is formatted with a thousand delimiter ','. When executed, the rule seems to consider only the digits on left of the comma, As a result, the threshold is limited to 100 lines of code per class.

Any ideas?
Thank you

David

**Comment by adangel** [comment]
There is no thousand delimiter, but a decimal delimiter. This property is currently of double type (although it doesn't make sense for a line count). The presentation of this double number depends on the locale eclipse is started with.

E.g. if the environment variable is `LANG=de_DE.UTF-8` is set, then the Spinner widget will display the (default) value 1000 as "1000,000" - since the decimal separator is a comma. If the variable is `LANG=en_US.UTF-8`, then the same number is displayed as "1000.000".

Unless you see both a comma and a dot as separators, I would assume that your comma is actually the decimal separator in your locale.

Feel free to reopen the issue if you still see a problem.
