### ISSUE TITLE
Upgrade PMD to 6.1.0

### ISSUE THREAD

**Issue by TehBakker** [pmd/pmd-eclipse-plugin#32]
Greetings,

I see PMD released PMD6 : https://github.com/pmd/pmd/releases#new-and-noteworthy
Wanted to know if / when you guys plan on updating the plugin to support it in the near futur ?

Regards

**Comment by adangel** [comment]
It planned in the near future, but bear in mind, that the whole project is done by volunteers. Any help is welcomed!

Btw. the current master branch works with PMD6, but there are some bugs, that should be fixed/analyzed before the release.

**Comment by TehBakker** [comment]
Thank you for the quick answer.
Yeah I'm very thankful for this project and the work done as by volunteers.

**Comment by adangel** [comment]
@TehBakker a new snapshot of the eclipse plugin with PMD 6.1.0 is now available :tada: 

Since sourceforge is not available at the moment, we needed to switch the update site completely to BinTray:

*   Releases: <https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/>
*   Snapshots: <https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/>

Could you please test it and provide feedback? Thanks!
