### ISSUE TITLE
Can not get pmd-eclipse-plugin 4.0.16

### ISSUE THREAD

**Issue by lonelyma1021** [pmd/pmd-eclipse-plugin#36]
I notice that the new version(4.0.16) is released. But I can't get it via https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/.It's still 4.0.15. And then I try to build it myself, but get a ClassNotFoundException: org.codehaus.plexus.components.io.fileselectors.FileInfo when running './mvnw clean verify'. 

By the way, the ruleset categories of PMD has changed since PMD 6.0.0, does it means all the custom rulesets used in 4.0.15 have to be rewrite?

**Comment by adangel** [comment]
Hi! 4.0.16 is not released yet, but there is a snapshot version available (just built from the master branch). If you want to try out this snapshot version, use https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/ as the update site (notice the "snapshots" in the url...).

The ruleset categories have indeed changed, but for PMD 6.0.0, the old rulesets still work (they just redirect to the new locations of the rules).

When you execute `./mvnw clean verify`, which java version do you use? Currently the eclipse plugin needs to be build with java8...

**Comment by lonelyma1021** [comment]
I excute `./mvnw clean verify` with OpenJDK 8 and Orcal JDK 8. And get the same error.

**Comment by adangel** [comment]
The class not found error might be caused by a corrupt download of a dependency (It can be a project dependency or a maven plugin dependency).
You could try to delete the files/directory under `~/.m2/repository/org/codehaus/plexus/plexus-io` and thus forcing maven to download the dependencies again with the next build. (`org.codehaus.plexus.components.io.fileselectors.FileInfo` is contained in org.codehaus.plexus:plexus-io).
